import React from 'react';
import { motion } from 'framer-motion';
import { Download, Share2, FileText, Sparkles, Copy } from 'lucide-react';

interface ReportViewProps {
    reportContent: string;
}

const ReportView: React.FC<ReportViewProps> = ({ reportContent }) => {
    const handleExportPDF = async () => {
        if (typeof window === 'undefined') return;

        try {
            const html2canvas = (await import('html2canvas')).default;
            const { jsPDF } = await import('jspdf');

            const element = document.getElementById('report-content');
            if (!element) return;

            // Capture the element using html2canvas
            const canvas = await html2canvas(element, {
                scale: 2,
                useCORS: true,
                logging: false,
                backgroundColor: '#050508', // Match the report background
                onclone: (clonedDoc) => {
                    const clonedElement = clonedDoc.getElementById('report-content');
                    if (clonedElement) {
                        // Force a white text color and dark background for the export
                        // since html2canvas sometimes struggles with complex inherited styles
                        clonedElement.style.color = '#ffffff';
                        clonedElement.style.backgroundColor = '#050508';

                        // Fix for oklch and other modern CSS if needed
                        const allElements = clonedElement.querySelectorAll('*');
                        allElements.forEach((el) => {
                            if (el instanceof HTMLElement) {
                                const style = window.getComputedStyle(el);
                                // If color is oklch, override it to something safe
                                if (style.color.includes('oklch')) {
                                    el.style.color = '#ffffff';
                                }
                            }
                        });
                    }
                }
            });

            const imgData = canvas.toDataURL('image/png');

            // PDF Preparation
            const pdf = new jsPDF('p', 'mm', 'a4');
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = pdf.internal.pageSize.getHeight();

            const imgWidth = pdfWidth;
            const imgHeight = (canvas.height * pdfWidth) / canvas.width;

            let heightLeft = imgHeight;
            let position = 0;

            // Page 1
            pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
            heightLeft -= pdfHeight;

            // Subsequent Pages
            while (heightLeft >= 0) {
                position = heightLeft - imgHeight;
                pdf.addPage();
                pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
                heightLeft -= pdfHeight;
            }

            pdf.save('Research_Report.pdf');
        } catch (error) {
            console.error('PDF Export failed', error);
            alert("Failed to export PDF. Please check the console for details.");
        }
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(reportContent);
        alert("Report copied to clipboard!");
    };

    return (
        <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            className="w-full max-w-5xl mx-auto"
        >
            <div className="glass-card rounded-2xl overflow-hidden shadow-2xl ring-1 ring-white/10">
                {/* Header */}
                <div className="px-6 py-4 border-b border-white/5 flex items-center justify-between bg-white/[0.02]">
                    <div className="flex items-center gap-3">
                        <div className="p-2 rounded-lg bg-purple-500/10 border border-purple-500/20 text-purple-400">
                            <Sparkles className="w-5 h-5" />
                        </div>
                        <div>
                            <h2 className="text-lg font-semibold text-white">Strategic Intelligence Report</h2>
                            <p className="text-xs text-gray-500">Generated by MAS Research Lab</p>
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <button
                            onClick={handleCopy}
                            className="p-2 hover:bg-white/10 rounded-lg transition-colors text-gray-400 hover:text-white"
                            title="Copy Text"
                        >
                            <Copy className="w-4 h-4" />
                        </button>
                        <button
                            onClick={handleExportPDF}
                            className="px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white rounded-lg flex items-center gap-2 transition-all font-medium text-sm shadow-[0_0_15px_-3px_rgba(168,85,247,0.4)] active:scale-95"
                        >
                            <Download className="w-4 h-4" />
                            <span>Export PDF</span>
                        </button>
                    </div>
                </div>

                {/* Content */}
                <div className="p-8 md:p-12 bg-[#050508] overflow-y-auto max-h-[70vh] custom-scrollbar">
                    {/* ID added for html2canvas target */}
                    <div id="report-content" className="prose prose-invert prose-purple max-w-none prose-headings:font-semibold prose-h1:text-3xl prose-h2:text-2xl prose-p:text-gray-300 prose-p:leading-relaxed prose-li:text-gray-300 bg-[#050508] p-4 text-white">
                        {/* 
                          In a real application, you should use `react-markdown` here.
                          For this demo, we are using `whitespace-pre-wrap` to preserve formatting from the raw text.
                        */}
                        <div className="whitespace-pre-wrap font-sans text-gray-300 text-base/7">
                            {reportContent || (
                                <div className="flex flex-col items-center justify-center py-20 text-gray-600 gap-4">
                                    <FileText className="w-12 h-12 opacity-20" />
                                    <p>Waiting for research analysis to complete...</p>
                                </div>
                            )}
                        </div>
                    </div>
                </div>

                <div className="px-6 py-3 border-t border-white/5 bg-black/40 text-[10px] text-gray-600 uppercase tracking-widest text-center">
                    Confidential • Generated by AI • Verify Independently
                </div>
            </div>
        </motion.div>
    );
};

export default ReportView;
